#!/usr/bin/env bash
# Configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sed -i 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
